{
 "title": "Zabbix - Nginx аналитика",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS rps\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE timestamp >= now() - INTERVAL 10 SECOND;"
    }
   ]
  },
  {
   "title": "Запросы/час",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS rps\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE timestamp >= now() - INTERVAL 1 HOUR;"
    }
   ]
  },
  {
   "title": "Уникальные IP за час",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uniq(remote_addr) AS unique_ips\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE timestamp >= now() - INTERVAL 1 HOUR;"
    }
   ]
  },
  {
   "title": "Ошибки за час",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS errors\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE timestamp >= now() - INTERVAL 1 HOUR\r\n  AND status >= 400;"
    }
   ]
  },
  {
   "title": "Макс размер ответа за час",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(body_bytes_sent) AS max_size\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE timestamp >= now() - INTERVAL 1 HOUR;"
    }
   ]
  },
  {
   "title": "Тяжелые запросы за час (более 10мб)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS slow_requests\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE timestamp >= now() - INTERVAL 1 HOUR\r\n  AND body_bytes_sent > 10000000;"
    }
   ]
  },
  {
   "title": "Запросы по времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(timestamp) AS time,\r\n    count(*) AS requests\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE\r\n    $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Статусы ответов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(timestamp) AS time,\r\n    countIf(status = 200) AS status_200,\r\n    countIf(status = 404) AS status_404,\r\n    countIf(status = 500) AS status_500,\r\n    countIf(status >= 400) AS errors\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE\r\n    $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Колво запросов по типам",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  if(isNaN(json_rpc), 0, json_rpc) AS \"JSON-RPC API\",\r\n  if(isNaN(js_rpc), 0, js_rpc) AS \"JS-RPC\",\r\n  if(isNaN(charts), 0, charts) AS \"Charts\",\r\n  if(isNaN(zabbix_ui), 0, zabbix_ui) AS \"Zabbix UI\",\r\n  if(isNaN(history), 0, history) AS \"History\",\r\n  if(isNaN(other), 0, other) AS \"Other\"\r\nFROM (\r\n  SELECT\r\n    toStartOfMinute(timestamp) AS time,\r\n    countIf(request LIKE '%api_jsonrpc.php%') AS json_rpc,\r\n    countIf(request LIKE '%jsrpc.php%') AS js_rpc,\r\n    countIf(request LIKE '%chart%') AS charts,\r\n    countIf(request LIKE '%zabbix.php%') AS zabbix_ui,\r\n    countIf(request LIKE '%history%') AS history,\r\n    countIf(NOT (\r\n      request LIKE '%api_jsonrpc.php%' OR\r\n      request LIKE '%jsrpc.php%' OR\r\n      request LIKE '%chart%' OR\r\n      request LIKE '%zabbix.php%' OR\r\n      request LIKE '%history%'\r\n    )) AS other\r\n  FROM zabbix_logs.nginx_access_extended\r\n  WHERE $__timeFilter(timestamp)\r\n  GROUP BY time\r\n)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Топ URL путей",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  request AS URL,\r\n  count(*) AS requests,\r\n  round(avg(body_bytes_sent)) AS avg_size,\r\n  countIf(status >= 400) AS errors,\r\n  round(100 * errors / requests, 2) AS error_rate\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY request\r\nORDER BY requests DESC\r\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Топ IP адресов",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  remote_addr AS IP,\r\n  count(*) AS requests,\r\n  countIf(status >= 400) AS errors,\r\n  round(avg(body_bytes_sent)) AS avg_size\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY remote_addr\r\nORDER BY requests DESC\r\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Самые тяжелые URL",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  request AS URL,\r\n  max(body_bytes_sent) AS max_size,\r\n  count(*) AS requests,\r\n  round(avg(body_bytes_sent)) AS avg_size\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND body_bytes_sent > 1000000\r\nGROUP BY request\r\nORDER BY max_size DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Топ по объему трафика",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  remote_addr AS IP,\r\n  sum(body_bytes_sent) AS total_size,\r\n  count(*) AS requests,\r\n  max(body_bytes_sent) AS max_request_size\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY remote_addr\r\nORDER BY total_size DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Максимальный размер запросов по типам",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  if(isNaN(json_rpc), 0, json_rpc) AS \"JSON-RPC API\",\r\n  if(isNaN(js_rpc), 0, js_rpc) AS \"JS-RPC\",\r\n  if(isNaN(charts), 0, charts) AS \"Charts\",\r\n  if(isNaN(zabbix_ui), 0, zabbix_ui) AS \"Zabbix UI\",\r\n  if(isNaN(history), 0, history) AS \"History\",\r\n  if(isNaN(other), 0, other) AS \"Other\"\r\nFROM (\r\n  SELECT\r\n    toStartOfMinute(timestamp) AS time,\r\n    maxIf(body_bytes_sent, request LIKE '%api_jsonrpc.php%') AS json_rpc,\r\n    maxIf(body_bytes_sent, request LIKE '%jsrpc.php%') AS js_rpc,\r\n    maxIf(body_bytes_sent, request LIKE '%chart%') AS charts,\r\n    maxIf(body_bytes_sent, request LIKE '%zabbix.php%') AS zabbix_ui,\r\n    maxIf(body_bytes_sent, request LIKE '%history%') AS history,\r\n    maxIf(body_bytes_sent, NOT (\r\n      request LIKE '%api_jsonrpc.php%' OR\r\n      request LIKE '%jsrpc.php%' OR\r\n      request LIKE '%chart%' OR\r\n      request LIKE '%zabbix.php%' OR\r\n      request LIKE '%history%'\r\n    )) AS other\r\n  FROM zabbix_logs.nginx_access_extended\r\n  WHERE\r\n    $__timeFilter(timestamp)\r\n    AND body_bytes_sent IS NOT NULL\r\n  GROUP BY time\r\n)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Общий размер запросов по типам",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  sumIf(body_bytes_sent, request LIKE '%api_jsonrpc.php%') AS \"JSON-RPC API\",\r\n  sumIf(body_bytes_sent, request LIKE '%jsrpc.php%') AS \"JS-RPC\",\r\n  sumIf(body_bytes_sent, request LIKE '%chart%') AS \"Charts\",\r\n  sumIf(body_bytes_sent, request LIKE '%zabbix.php%') AS \"Zabbix UI\",\r\n  sumIf(body_bytes_sent, request LIKE '%history%') AS \"History\",\r\n  sumIf(body_bytes_sent, NOT (\r\n    request LIKE '%api_jsonrpc.php%' OR\r\n    request LIKE '%jsrpc.php%' OR\r\n    request LIKE '%chart%' OR\r\n    request LIKE '%zabbix.php%' OR\r\n    request LIKE '%history%'\r\n  )) AS \"Other\"\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND body_bytes_sent IS NOT NULL\r\nGROUP BY toStartOfMinute(timestamp) AS time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Типы запросов",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN request LIKE '%api_jsonrpc.php%' THEN 'JSON-RPC API'\r\n    WHEN request LIKE '%jsrpc.php%' THEN 'JS-RPC'\r\n    WHEN request LIKE '%chart%' THEN 'Charts'\r\n    WHEN request LIKE '%history%' THEN 'History'\r\n    WHEN request LIKE '%zabbix.php%' THEN 'Zabbix UI'\r\n    ELSE 'Other'\r\n  END AS type,\r\n  count(*) AS requests\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY type\r\nORDER BY requests DESC;"
    }
   ]
  },
  {
   "title": "Топ ошибок",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  status,\r\n  request,\r\n  count(*) AS errors\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND status >= 400\r\nGROUP BY status, request\r\nORDER BY errors DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Топ User Agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  http_user_agent,\r\n  count(*) AS requests\r\nFROM zabbix_logs.nginx_access_extended\r\nWHERE\r\n  $__timeFilter(timestamp)\r\n  AND http_user_agent != '-'\r\nGROUP BY http_user_agent\r\nORDER BY requests DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}